# Generated by Django 5.1 on 2024-09-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_post_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update',
            new_name='updated',
        ),
    ]
