# Generated by Django 5.1 on 2024-09-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_update_post_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
