# Generated by Django 5.1 on 2024-09-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_post_body_remove_post_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
