# Generated by Django 5.1 on 2024-09-05 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
